# -*- coding: utf-8 -*-
"""FinalEmotionClassification_v3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u-s3fmPdJ4f8suIvUWX11Kp5xXiXwgcR

# FinalEmotionClassification v3 — High-Accuracy Emotion Classifier

**Goal:** Maximize exact-match accuracy on GoEmotions 28-class classification.

**Key v3 improvements over v1/v2:**
- Single-label rows only (no multi-label contamination)
- Class codes L00–L27 (single-token targets, no parsing ambiguity)
- Compact prompt format (minimal wasted tokens)
- Loss masking on label tokens only (DataCollatorForCompletionOnlyLM)
- Closed-set scoring evaluation (eliminates invalid outputs)
- Overfit sanity check before full training
- Full test-set evaluation
- Validation-driven checkpoint selection

**Stack:** Llama 3.2 1B · 4-bit QLoRA · Unsloth · Google Colab · Ollama deployment

## Block 1 — Install Dependencies
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install unsloth
# !pip install datasets scikit-learn evaluate sentencepiece safetensors

"""## Block 2 — Environment & GPU Check"""

import sys, torch

print(f"Python  : {sys.version}")
print(f"PyTorch : {torch.__version__}")
print(f"CUDA    : {torch.cuda.is_available()}")

if not torch.cuda.is_available():
    raise RuntimeError("No GPU — enable GPU in Runtime > Change runtime type.")

gpu_name = torch.cuda.get_device_name(0)
gpu_mem = torch.cuda.get_device_properties(0).total_memory / 1e9
print(f"GPU     : {gpu_name} ({gpu_mem:.1f} GB)")

IS_LOW_MEM = gpu_mem < 20
if IS_LOW_MEM:
    print("Low-memory GPU detected — using conservative batch sizes.")

"""## Block 3 — Configuration, Labels & Reproducibility

All 28 GoEmotions labels mapped to compact codes L00–L27. The code→label mapping
is used end-to-end: dataset creation, training targets, parser, evaluation, inference,
and Ollama export.
"""

import os, gc, json, random, hashlib, unicodedata, re, warnings, time
from dataclasses import dataclass, field, asdict
from collections import Counter
from typing import List, Dict, Optional, Tuple

import numpy as np
import pandas as pd
import torch
import matplotlib.pyplot as plt
from sklearn.metrics import (
    classification_report, confusion_matrix, accuracy_score,
    precision_recall_fscore_support, f1_score,
)
from datasets import load_dataset, Dataset, DatasetDict

warnings.filterwarnings("ignore", category=FutureWarning)
warnings.filterwarnings("ignore", category=UserWarning)

# ── 28 GoEmotions labels ──────────────────────────────────────────────────────
LABEL_NAMES = [
    "admiration", "amusement", "anger", "annoyance", "approval",
    "caring", "confusion", "curiosity", "desire", "disappointment",
    "disapproval", "disgust", "embarrassment", "excitement", "fear",
    "gratitude", "grief", "joy", "love", "nervousness",
    "optimism", "pride", "realization", "relief", "remorse",
    "sadness", "surprise", "neutral",
]
NUM_LABELS = len(LABEL_NAMES)

# Code ↔ label mappings (used everywhere end-to-end)
IDX2NAME = {i: name for i, name in enumerate(LABEL_NAMES)}
NAME2IDX = {name: i for i, name in enumerate(LABEL_NAMES)}
IDX2CODE = {i: f"L{i:02d}" for i in range(NUM_LABELS)}
CODE2IDX = {v: k for k, v in IDX2CODE.items()}
CODE2NAME = {IDX2CODE[i]: name for i, name in enumerate(LABEL_NAMES)}
NAME2CODE = {name: IDX2CODE[i] for i, name in enumerate(LABEL_NAMES)}

print("Label mapping:")
for i in range(NUM_LABELS):
    print(f"  {IDX2CODE[i]} = {LABEL_NAMES[i]}")

# ── Config ─────────────────────────────────────────────────────────────────────
@dataclass
class Config:
    model_name: str = "unsloth/Llama-3.2-1B-Instruct-bnb-4bit"
    max_seq_length: int = 256

    lora_r: int = 64
    lora_alpha: int = 128
    lora_dropout: float = 0.05

    num_train_epochs: int = 4
    train_batch_size: int = 4 if IS_LOW_MEM else 8
    eval_batch_size: int = 4 if IS_LOW_MEM else 8
    gradient_accumulation_steps: int = 8 if IS_LOW_MEM else 4
    learning_rate: float = 1e-4
    weight_decay: float = 0.01
    warmup_ratio: float = 0.06
    lr_scheduler_type: str = "cosine"

    eval_steps: int = 200
    save_steps: int = 200
    save_total_limit: int = 3
    logging_steps: int = 25
    early_stopping_patience: int = 4

    seed: int = 42
    output_dir: str = "/content/emotion_v3"

    debug_mode: bool = False
    debug_n: int = 500

config = Config()

def set_seed(seed):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)
    os.environ["PYTHONHASHSEED"] = str(seed)

set_seed(config.seed)

DIRS = {k: f"{config.output_dir}/{k}" for k in ["model", "plots", "results", "gguf"]}
for d in DIRS.values():
    os.makedirs(d, exist_ok=True)

print(f"\nConfig:\n{json.dumps({k: str(v) for k, v in asdict(config).items()}, indent=2)}")

"""## Block 4 — Dataset Loading (Single-Label Only)

Loads the official GoEmotions simplified dataset and **keeps only rows with exactly
one label**. This is critical — taking `labels[0]` from multi-label rows introduces
label noise that directly harms exact-match accuracy. Single-label-only gives the
cleanest training signal.
"""

print("Loading GoEmotions (simplified)...\n")
raw_ds = load_dataset("google-research-datasets/go_emotions", "simplified")
for sn in raw_ds:
    print(f"  {sn}: {len(raw_ds[sn]):,} rows")

# ── Keep ONLY single-label rows ──────────────────────────────────────────────
def is_single_label(example):
    return len(example["labels"]) == 1

ds = raw_ds.filter(is_single_label)

for sn in ds:
    kept = len(ds[sn])
    orig = len(raw_ds[sn])
    print(f"  {sn}: {orig:,} -> {kept:,} single-label ({100*kept/orig:.1f}% kept)")

# ── Add label fields ──────────────────────────────────────────────────────────
def add_label_fields(example):
    idx = example["labels"][0]
    return {
        "label_idx": idx,
        "label_name": IDX2NAME[idx],
        "label_code": IDX2CODE[idx],
    }

ds = ds.map(add_label_fields)

# ── Stats ─────────────────────────────────────────────────────────────────────
print(f"\n--- Train Label Distribution ---")
train_counts = Counter(x["label_name"] for x in ds["train"])
for name in LABEL_NAMES:
    c = train_counts.get(name, 0)
    print(f"  {name:20s} {c:5d}")

lengths = np.array([len(x["text"]) for x in ds["train"]])
print(f"\nText length (chars): min={lengths.min()}, max={lengths.max()}, "
      f"mean={lengths.mean():.0f}, p95={np.percentile(lengths,95):.0f}")

# ── Check for empty/null ──────────────────────────────────────────────────────
for sn in ds:
    bad = sum(1 for x in ds[sn] if not x["text"] or not x["text"].strip())
    assert bad == 0, f"{sn} has {bad} empty texts!"
    print(f"  {sn}: {len(ds[sn]):,} rows, 0 empty texts, all labels valid")

print(f"\nTotal single-label examples: {sum(len(ds[sn]) for sn in ds):,}")

"""## Block 5 — Data Audit & Leakage Prevention

Full integrity check: duplicates, cross-split leakage, label cardinality.
Saves audit summary to disk.
"""

print("=== Data Audit ===\n")

def norm(text):
    return re.sub(r"\s+", " ", text.lower().strip())

# ── Within-split duplicates ───────────────────────────────────────────────────
for sn in ds:
    texts = [norm(x["text"]) for x in ds[sn]]
    n_dup = len(texts) - len(set(texts))
    print(f"  {sn}: {n_dup} duplicate texts")

# ── Cross-split leakage ──────────────────────────────────────────────────────
splits = {sn: set(norm(x["text"]) for x in ds[sn]) for sn in ds}
tv = splits["train"] & splits["validation"]
tt = splits["train"] & splits["test"]
vt = splits["validation"] & splits["test"]
print(f"\n  Cross-split overlap: train&val={len(tv)}, train&test={len(tt)}, val&test={len(vt)}")

# Remove leaked rows from val/test
if tv:
    ds["validation"] = ds["validation"].filter(lambda x: norm(x["text"]) not in tv)
    print(f"  Removed {len(tv)} leaked rows from validation")
if tt or vt:
    leak = tt | vt
    ds["test"] = ds["test"].filter(lambda x: norm(x["text"]) not in leak)
    print(f"  Removed {len(leak)} leaked rows from test")

# ── Deduplicate within splits ─────────────────────────────────────────────────
for sn in list(ds.keys()):
    df = ds[sn].to_pandas()
    before = len(df)
    df["_n"] = df["text"].apply(norm)
    df = df.drop_duplicates(subset=["_n", "label_idx"], keep="first").drop(columns=["_n"])
    if len(df) < before:
        print(f"  Deduped {sn}: {before} -> {len(df)}")
    ds[sn] = Dataset.from_pandas(df, preserve_index=False)

# ── Label cardinality ─────────────────────────────────────────────────────────
for sn in ds:
    present = set(x["label_idx"] for x in ds[sn])
    missing = set(range(NUM_LABELS)) - present
    if missing:
        print(f"  WARNING {sn} missing: {[IDX2NAME[i] for i in missing]}")
    else:
        print(f"  {sn}: all {NUM_LABELS} labels present")

# ── Save audit ────────────────────────────────────────────────────────────────
audit = {sn: {"rows": len(ds[sn]), "labels": len(set(x["label_idx"] for x in ds[sn]))} for sn in ds}
with open(f"{DIRS['results']}/audit.json", "w") as f:
    json.dump(audit, f, indent=2)

print("\n--- Final Counts ---")
for sn in ds:
    print(f"  {sn:12s}: {len(ds[sn]):,}")

"""## Block 6 — Preprocessing + Post-Preprocessing Leakage Check"""

print("=== Preprocessing ===\n")

def preprocess(text):
    if not text:
        return ""
    text = unicodedata.normalize("NFKC", text)
    text = re.sub(r"[\x00-\x08\x0b\x0c\x0e-\x1f\x7f-\x9f]", "", text)
    text = re.sub(r"https?://\S+|www\.\S+", "[URL]", text)
    text = re.sub(r"\bu/\w+", "[USER]", text)
    text = re.sub(r"@\w+", "[USER]", text)
    text = re.sub(r"\br/\w+", "[SUB]", text)
    text = re.sub(r"[ \t]+", " ", text)
    return text.strip()

ds = ds.map(lambda x: {"text_orig": x["text"], "text": preprocess(x["text"])})

for sn in ds:
    changed = sum(1 for x in ds[sn] if x["text"] != x["text_orig"])
    empty = sum(1 for x in ds[sn] if not x["text"].strip())
    print(f"  {sn}: {changed} modified, {empty} empty after preprocessing")
    assert empty == 0, f"Preprocessing created empty texts in {sn}!"

# ── Post-preprocessing leakage re-check ───────────────────────────────────────
print("\n--- Post-Preprocessing Leakage Re-check ---")
pp_splits = {sn: set(norm(x["text"]) for x in ds[sn]) for sn in ds}
pp_tv = pp_splits["train"] & pp_splits["validation"]
pp_tt = pp_splits["train"] & pp_splits["test"]
print(f"  train&val={len(pp_tv)}, train&test={len(pp_tt)}")

if pp_tv:
    ds["validation"] = ds["validation"].filter(lambda x: norm(x["text"]) not in pp_tv)
    print(f"  Removed {len(pp_tv)} from validation")
if pp_tt:
    ds["test"] = ds["test"].filter(lambda x: norm(x["text"]) not in pp_tt)
    print(f"  Removed {len(pp_tt)} from test")

# Re-dedup on preprocessed text
for sn in list(ds.keys()):
    df = ds[sn].to_pandas()
    before = len(df)
    df["_n"] = df["text"].apply(norm)
    df = df.drop_duplicates(subset=["_n", "label_idx"], keep="first").drop(columns=["_n"])
    if len(df) < before:
        print(f"  Re-deduped {sn}: {before} -> {len(df)}")
    ds[sn] = Dataset.from_pandas(df, preserve_index=False)

print("\n--- After All Cleaning ---")
for sn in ds:
    print(f"  {sn:12s}: {len(ds[sn]):,}")

"""## Block 7 — Format Data with Class Codes

Creates a compact instruction-completion format:
```
Classify the emotion.\nText: <text>\nLabel: L<nn>
```
Class codes L00–L27 are single fixed-width tokens. The label boundary after
"Label: " is where loss masking starts — only the code tokens are supervised.
"""

print("=== Format with Class Codes ===\n")

PROMPT_TEMPLATE = "Classify the emotion.\nText: {text}\nLabel: "

def format_example(example):
    prompt = PROMPT_TEMPLATE.format(text=example["text"])
    code = example["label_code"]
    example["prompt"] = prompt
    example["completion"] = code
    example["text_formatted"] = prompt + code
    return example

ds = ds.map(format_example)

# Show samples
for i in range(3):
    ex = ds["train"][i]
    print(f"[{i}] {repr(ex['text_formatted'][:120])}")
    print(f"     prompt ends at: ...{repr(ex['prompt'][-20:])}")
    print(f"     completion: {ex['completion']} = {CODE2NAME[ex['completion']]}")
    print()

# Save label mapping
with open(f"{DIRS['results']}/label_mapping.json", "w") as f:
    json.dump({"code_to_name": CODE2NAME, "name_to_code": NAME2CODE}, f, indent=2)
print(f"Label mapping saved to {DIRS['results']}/label_mapping.json")

"""## Block 8 — Model Loading with Unsloth + LoRA

LoRA r=64 with alpha=128 targets all projections for maximum capacity on the
28-class task. Higher rank than v1 because we are optimizing for accuracy.
"""

print("=== Model Loading ===\n")

from unsloth import FastLanguageModel, is_bfloat16_supported

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name=config.model_name,
    max_seq_length=config.max_seq_length,
    dtype=None,
    load_in_4bit=True,
)

model = FastLanguageModel.get_peft_model(
    model,
    r=config.lora_r,
    lora_alpha=config.lora_alpha,
    lora_dropout=config.lora_dropout,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj",
                     "gate_proj", "up_proj", "down_proj"],
    bias="none",
    use_gradient_checkpointing="unsloth",
    random_state=config.seed,
)

trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
total_p = sum(p.numel() for p in model.parameters())
print(f"Trainable: {trainable:,} / {total_p:,} ({100*trainable/total_p:.2f}%)")
print(f"LoRA r={config.lora_r}, alpha={config.lora_alpha}")

"""## Block 9 — Tokenization Analysis & Loss Masking Verification

Verifies that:
1. Token lengths fit within `max_seq_length` with minimal truncation.
2. The DataCollatorForCompletionOnlyLM correctly masks all prompt tokens
   and only supervises the label code tokens.
"""

print("=== Tokenization Analysis ===\n")

# ── Token lengths ─────────────────────────────────────────────────────────────
sample = [x["text_formatted"] for x in ds["train"]][:3000]
tok_lens = [len(tokenizer(t, add_special_tokens=True).input_ids) for t in sample]
tok_lens = np.array(tok_lens)

print(f"Token lengths (n={len(tok_lens)}):")
print(f"  min={tok_lens.min()}, mean={tok_lens.mean():.0f}, "
      f"p95={np.percentile(tok_lens,95):.0f}, max={tok_lens.max()}")
trunc = (tok_lens > config.max_seq_length).sum()
print(f"  Truncated at {config.max_seq_length}: {trunc} ({100*trunc/len(tok_lens):.1f}%)")

fig, ax = plt.subplots(figsize=(10, 3))
ax.hist(tok_lens, bins=50, color="teal", edgecolor="white")
ax.axvline(config.max_seq_length, color="red", ls="--", label=f"max={config.max_seq_length}")
ax.set_xlabel("Tokens")
ax.set_ylabel("Count")
ax.legend()
plt.tight_layout()
plt.savefig(f"{DIRS['plots']}/token_lengths.png", dpi=150)
plt.show()

# ── Verify loss masking (custom collator; robust template matching) ──────────
print("\n--- Loss Masking Sanity Check ---")

class CompletionOnlyCollator:
    """
    Masks prompt tokens with -100, keeps only completion tokens (label code)
    for loss computation.
    """
    def __init__(self, tokenizer, response_templates, max_length):
        self.tokenizer = tokenizer
        self.max_length = max_length

        # Support multiple template variants for tokenizer edge cases
        if isinstance(response_templates, str):
            response_templates = [response_templates]

        self.response_templates = response_templates
        self.response_ids_list = []
        for t in response_templates:
            ids = tokenizer.encode(t, add_special_tokens=False)
            if len(ids) > 0:
                self.response_ids_list.append((t, ids))

        if len(self.response_ids_list) == 0:
            raise ValueError("All response templates tokenized to empty IDs.")

    @staticmethod
    def _find_subseq(seq, subseq):
        n, m = len(seq), len(subseq)
        for i in range(n - m + 1):
            if seq[i:i+m] == subseq:
                return i
        return -1

    def _to_feature(self, f):
        # Works with pretokenized features or raw rows
        if "input_ids" in f and "attention_mask" in f:
            return {"input_ids": f["input_ids"], "attention_mask": f["attention_mask"]}
        if "text_formatted" in f:
            tok = self.tokenizer(
                f["text_formatted"],
                truncation=True,
                max_length=self.max_length,
                add_special_tokens=True,
            )
            return {"input_ids": tok["input_ids"], "attention_mask": tok["attention_mask"]}
        raise KeyError(f"Feature missing required fields: {f.keys()}")

    def __call__(self, features):
        feats = [self._to_feature(f) for f in features]
        batch = self.tokenizer.pad(feats, return_tensors="pt")

        input_ids = batch["input_ids"]
        attention_mask = batch["attention_mask"]
        labels = input_ids.clone()

        for i in range(input_ids.size(0)):
            valid_len = int(attention_mask[i].sum().item())
            seq = input_ids[i, :valid_len].tolist()

            # Try all template variants and pick first match
            found_start = -1
            found_len = 0
            found_template = None
            for t, ids in self.response_ids_list:
                s = self._find_subseq(seq, ids)
                if s != -1:
                    found_start = s
                    found_len = len(ids)
                    found_template = t
                    break

            if found_start == -1:
                # Safe fallback: mask whole sequence
                labels[i, :valid_len] = -100
            else:
                label_start = found_start + found_len
                labels[i, :label_start] = -100

            # Mask padding
            labels[i, valid_len:] = -100

        batch["labels"] = labels
        return batch

# Use multiple variants because tokenizer behavior can differ by version/model
response_templates = ["\nLabel: ", "\nLabel:", "Label: ", "Label:"]
print("Template token IDs:")
for t in response_templates:
    print(f"  {repr(t)} -> {tokenizer.encode(t, add_special_tokens=False)}")

collator = CompletionOnlyCollator(
    tokenizer=tokenizer,
    response_templates=response_templates,
    max_length=config.max_seq_length,
)

# Test on one example
test_ex = ds["train"][0]
test_tok = tokenizer(
    test_ex["text_formatted"],
    add_special_tokens=True,
    return_tensors="pt",
    truncation=True,
    max_length=config.max_seq_length,
)

batch = collator([{
    "input_ids": test_tok.input_ids[0].tolist(),
    "attention_mask": test_tok.attention_mask[0].tolist(),
}])

labels = batch["labels"][0]
input_ids = batch["input_ids"][0]
supervised_mask = labels != -100
supervised_tokens = tokenizer.decode(input_ids[supervised_mask])

masked_count = int((labels == -100).sum().item())
supervised_count = int(supervised_mask.sum().item())

print(f"\nTotal tokens: {len(labels)}")
print(f"Masked (prompt): {masked_count}")
print(f"Supervised (label): {supervised_count}")
print(f"Supervised text: {repr(supervised_tokens)}")
print(f"Expected code: '{test_ex['completion']}' = {CODE2NAME[test_ex['completion']]}")

assert supervised_count > 0, "ERROR: No tokens are supervised! Check response template matching."
assert supervised_count < 10, f"WARNING: {supervised_count} supervised tokens seems high for a code."

print("\nMasking verified — only label code tokens are supervised.")

"""## Block 10 — Overfit Sanity Check

Trains on 256 examples for ~100 steps. If the model can nearly memorize this
subset (>90% accuracy), the pipeline is correct. If not, something is broken.
"""

print("=== Overfit Sanity Check ===\n")

from trl import SFTTrainer
from transformers import TrainingArguments

set_seed(config.seed)

# Remove raw HF labels column if present
drop_cols = [c for c in ["labels"] if c in ds["train"].column_names]
overfit_base = ds["train"].remove_columns(drop_cols) if drop_cols else ds["train"]

overfit_n = 256
overfit_ds = overfit_base.select(range(min(overfit_n, len(overfit_base))))
print(f"Overfit subset: {len(overfit_ds)} examples")
print(f"Columns used: {overfit_ds.column_names}")

required = {"prompt", "completion", "text", "label_code"}
missing = required - set(overfit_ds.column_names)
if missing:
    raise KeyError(f"Missing required columns for completion training: {missing}")

# IMPORTANT:
# - no custom collator
# - no dataset_text_field
# SFTTrainer will use prompt+completion and internal completion_mask handling
overfit_trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=overfit_ds,
    max_seq_length=config.max_seq_length,
    packing=False,
    args=TrainingArguments(
        per_device_train_batch_size=config.train_batch_size,
        gradient_accumulation_steps=2,
        num_train_epochs=10,
        learning_rate=config.learning_rate,
        fp16=not is_bfloat16_supported(),
        bf16=is_bfloat16_supported(),
        logging_steps=10,
        optim="adamw_8bit",
        output_dir=f"{config.output_dir}/overfit_check",
        report_to="none",
        seed=config.seed,
        remove_unused_columns=False,
    ),
)

overfit_trainer.train()

last_loss = next((x["loss"] for x in reversed(overfit_trainer.state.log_history) if "loss" in x), None)
print(f"Overfit train loss: {last_loss}")

# Quick memorization check
FastLanguageModel.for_inference(model)
correct = 0
eval_n = min(50, len(overfit_ds))

for i in range(eval_n):
    text = overfit_ds[i]["text"]
    true_code = overfit_ds[i]["label_code"]

    prompt = PROMPT_TEMPLATE.format(text=text)
    inputs = tokenizer(
        prompt,
        return_tensors="pt",
        truncation=True,
        max_length=config.max_seq_length
    ).to(model.device)

    with torch.no_grad():
        out = model.generate(**inputs, max_new_tokens=8, do_sample=False, use_cache=True)

    pred = tokenizer.decode(out[0][inputs.input_ids.shape[1]:], skip_special_tokens=True).strip()
    if pred.startswith(true_code):
        correct += 1

acc = correct / eval_n
print(f"\nOverfit accuracy (first {eval_n}): {acc:.2%}")
if acc < 0.5:
    print("WARNING: Overfit accuracy < 50%. Check pipeline before full training.")
elif acc < 0.9:
    print("Partial pass: model is learning, but not near-memorizing yet.")
else:
    print("Overfit check passed — pipeline appears correct.")

model.train()
gc.collect()
torch.cuda.empty_cache()

"""## Block 11 — Full Training

SFTTrainer with:
- DataCollatorForCompletionOnlyLM (loss on label tokens only)
- Cosine LR with warmup
- Early stopping (patience=4 eval steps)
- Best checkpoint by eval loss
"""

print("=== Full Training ===\n")

from trl import SFTTrainer
from transformers import TrainingArguments, EarlyStoppingCallback
from math import ceil

# Remove raw HF labels column if present
drop_cols = [c for c in ["labels"] if c in ds["train"].column_names]
train_base = ds["train"].remove_columns(drop_cols) if drop_cols else ds["train"]
eval_base  = ds["validation"].remove_columns(drop_cols) if drop_cols else ds["validation"]

if config.debug_mode:
    train_data = train_base.select(range(min(config.debug_n, len(train_base))))
    eval_data  = eval_base.select(range(min(config.debug_n // 4, len(eval_base))))
else:
    train_data = train_base
    eval_data  = eval_base

required_cols = {"prompt", "completion", "text", "label_code"}
missing_train = required_cols - set(train_data.column_names)
missing_eval = required_cols - set(eval_data.column_names)
if missing_train:
    raise KeyError(f"Train dataset missing required columns: {missing_train}")
if missing_eval:
    raise KeyError(f"Eval dataset missing required columns: {missing_eval}")

# ── CRITICAL FIX: filter out overlength rows before SFTTrainer tokenization ───
# This avoids completion_mask/input_ids truncation mismatch in fused loss.
def add_seq_len(example):
    ids = tokenizer(
        example["prompt"] + example["completion"],
        add_special_tokens=True,
        truncation=False
    )["input_ids"]
    return {"seq_len": len(ids)}

print("Computing sequence lengths...")
train_data = train_data.map(add_seq_len, num_proc=2)
eval_data  = eval_data.map(add_seq_len, num_proc=2)

train_before, eval_before = len(train_data), len(eval_data)
train_data = train_data.filter(lambda x: x["seq_len"] <= config.max_seq_length)
eval_data  = eval_data.filter(lambda x: x["seq_len"] <= config.max_seq_length)

train_after, eval_after = len(train_data), len(eval_data)
print(f"Train rows kept: {train_after:,}/{train_before:,} "
      f"(removed {train_before - train_after:,})")
print(f"Eval rows kept : {eval_after:,}/{eval_before:,} "
      f"(removed {eval_before - eval_after:,})")

if train_after == 0 or eval_after == 0:
    raise RuntimeError(
        "All rows removed by max_seq_length filter. Increase config.max_seq_length."
    )

# sanity check: no overlength rows remain
max_train_len = max(train_data["seq_len"])
max_eval_len = max(eval_data["seq_len"])
print(f"Max seq_len after filter — train: {max_train_len}, eval: {max_eval_len}")
assert max_train_len <= config.max_seq_length
assert max_eval_len <= config.max_seq_length

# Drop helper column (not needed for training)
train_data = train_data.remove_columns(["seq_len"])
eval_data = eval_data.remove_columns(["seq_len"])

eff_bs = config.train_batch_size * config.gradient_accumulation_steps
steps_per_epoch = ceil(len(train_data) / eff_bs)
total_steps = steps_per_epoch * config.num_train_epochs
warmup_steps = max(20, int(0.06 * total_steps))  # replaces warmup_ratio

print(f"\nTrain: {len(train_data):,} | Eval: {len(eval_data):,}")
print(f"Effective BS: {eff_bs} | Epochs: {config.num_train_epochs}")
print(f"Total steps: {total_steps} | Warmup steps: {warmup_steps}")
print(f"LR: {config.learning_rate} | Scheduler: {config.lr_scheduler_type}")
print(f"Mixed precision: {'bf16' if is_bfloat16_supported() else 'fp16'}")
print(f"Train columns: {train_data.column_names}\n")

trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=train_data,
    eval_dataset=eval_data,
    max_seq_length=config.max_seq_length,
    dataset_num_proc=2,
    packing=False,
    args=TrainingArguments(
        per_device_train_batch_size=config.train_batch_size,
        per_device_eval_batch_size=config.eval_batch_size,
        gradient_accumulation_steps=config.gradient_accumulation_steps,
        num_train_epochs=config.num_train_epochs,
        learning_rate=config.learning_rate,
        warmup_steps=warmup_steps,            # <-- no warmup_ratio warning
        fp16=not is_bfloat16_supported(),
        bf16=is_bfloat16_supported(),
        logging_steps=config.logging_steps,
        optim="adamw_8bit",
        weight_decay=config.weight_decay,
        lr_scheduler_type=config.lr_scheduler_type,
        seed=config.seed,
        output_dir=config.output_dir,
        eval_strategy="steps",
        eval_steps=config.eval_steps,
        save_strategy="steps",
        save_steps=config.save_steps,
        save_total_limit=config.save_total_limit,
        load_best_model_at_end=True,
        metric_for_best_model="eval_loss",
        greater_is_better=False,
        report_to="none",
        remove_unused_columns=False,
    ),
    callbacks=[EarlyStoppingCallback(early_stopping_patience=config.early_stopping_patience)],
)

start = time.time()
result = trainer.train()
elapsed = time.time() - start
print(f"\nDone in {elapsed/60:.1f} min | Loss: {result.training_loss:.4f}")

# ── Loss curves ───────────────────────────────────────────────────────────────
hist = trainer.state.log_history
t_loss = [(h["step"], h["loss"]) for h in hist if "loss" in h]
e_loss = [(h["step"], h["eval_loss"]) for h in hist if "eval_loss" in h]

fig, ax = plt.subplots(figsize=(10, 4))
if t_loss:
    ax.plot(*zip(*t_loss), label="Train", alpha=0.7)
if e_loss:
    s, l = zip(*e_loss)
    ax.plot(s, l, label="Eval", lw=2)
    best_i = int(np.argmin(l))
    ax.scatter([s[best_i]], [l[best_i]], c="red", zorder=5,
               label=f"Best={l[best_i]:.4f} @ {s[best_i]}")
ax.set_xlabel("Step")
ax.set_ylabel("Loss")
ax.legend()
ax.grid(alpha=0.3)
plt.tight_layout()
plt.savefig(f"{DIRS['plots']}/loss.png", dpi=150)
plt.show()

"""## Block 12 — Closed-Set Scoring Function

Instead of free-form generation, we compute the log-probability of each of the
28 label codes given the prompt prefix. The code with the highest probability wins.
This eliminates invalid outputs entirely and is the primary evaluation method.
"""

print("=== Closed-Set Scoring Setup ===\n")

FastLanguageModel.for_inference(model)

# Pre-tokenize all 28 codes
CODE_TOKEN_IDS = {}
for idx in range(NUM_LABELS):
    code_str = IDX2CODE[idx]
    ids = tokenizer.encode(code_str, add_special_tokens=False)
    CODE_TOKEN_IDS[idx] = ids

print("Code tokenizations:")
for idx in range(NUM_LABELS):
    ids = CODE_TOKEN_IDS[idx]
    decoded = tokenizer.decode(ids)
    print(f"  {IDX2CODE[idx]} ({IDX2NAME[idx]:20s}) -> {ids} -> '{decoded}'")

def closed_set_predict(text: str) -> tuple:
    """Score all 28 label codes, return (predicted_name, predicted_code, scores_dict)."""
    prompt = PROMPT_TEMPLATE.format(text=text)
    prompt_ids = tokenizer.encode(prompt, add_special_tokens=True)
    prompt_len = len(prompt_ids)

    best_idx = -1
    best_score = float("-inf")
    all_scores = {}

    for idx in range(NUM_LABELS):
        code_ids = CODE_TOKEN_IDS[idx]
        full_ids = prompt_ids + code_ids
        input_tensor = torch.tensor([full_ids], device=model.device)

        with torch.no_grad():
            outputs = model(input_tensor)

        logits = outputs.logits[0]
        log_probs = torch.log_softmax(logits, dim=-1)

        total_lp = 0.0
        for i, tid in enumerate(code_ids):
            pos = prompt_len - 1 + i
            total_lp += log_probs[pos, tid].item()

        all_scores[idx] = total_lp
        if total_lp > best_score:
            best_score = total_lp
            best_idx = idx

    return IDX2NAME[best_idx], IDX2CODE[best_idx], all_scores

# Quick test
test_name, test_code, test_scores = closed_set_predict("I'm so happy today!")
print(f"\nTest: 'I'm so happy today!' -> {test_code} ({test_name})")
top3 = sorted(test_scores.items(), key=lambda x: x[1], reverse=True)[:3]
for idx, score in top3:
    print(f"  {IDX2CODE[idx]} ({IDX2NAME[idx]}): {score:.4f}")

"""## Block 13 — Full Test Evaluation (Closed-Set Scoring)

Evaluates on the **entire** test set using closed-set scoring.
This is the primary accuracy metric — no parsing, no invalid outputs.
"""

print("=== Full Test Evaluation (Closed-Set) ===\n")

test_texts = [x["text"] for x in ds["test"]]
test_true_names = [x["label_name"] for x in ds["test"]]
test_true_codes = [x["label_code"] for x in ds["test"]]

n_test = len(test_texts)
print(f"Evaluating {n_test:,} test examples with closed-set scoring...\n")

pred_names = []
pred_codes = []
for i, text in enumerate(test_texts):
    name, code_str, _ = closed_set_predict(text)
    pred_names.append(name)
    pred_codes.append(code_str)
    if (i + 1) % 200 == 0 or i + 1 == n_test:
        print(f"  {i+1:,}/{n_test:,}", end="\r")

print()

# ── Metrics ───────────────────────────────────────────────────────────────────
acc = accuracy_score(test_true_names, pred_names)
m_p, m_r, m_f1, _ = precision_recall_fscore_support(
    test_true_names, pred_names, average="macro", zero_division=0)
w_p, w_r, w_f1, _ = precision_recall_fscore_support(
    test_true_names, pred_names, average="weighted", zero_division=0)

print(f"\n{'='*50}")
print(f"  CLOSED-SET RESULTS (n={n_test:,})")
print(f"  Accuracy          : {acc:.4f}")
print(f"  Macro Precision   : {m_p:.4f}")
print(f"  Macro Recall      : {m_r:.4f}")
print(f"  Macro F1          : {m_f1:.4f}")
print(f"  Weighted Precision: {w_p:.4f}")
print(f"  Weighted Recall   : {w_r:.4f}")
print(f"  Weighted F1       : {w_f1:.4f}")
print(f"  Invalid outputs   : 0 (closed-set)")
print(f"{'='*50}")

# ── Classification report ─────────────────────────────────────────────────────
print("\n--- Classification Report ---")
print(classification_report(test_true_names, pred_names, labels=LABEL_NAMES,
                            target_names=LABEL_NAMES, zero_division=0))

# ── Save metrics ──────────────────────────────────────────────────────────────
metrics = {
    "accuracy": round(acc, 4), "macro_f1": round(m_f1, 4), "weighted_f1": round(w_f1, 4),
    "macro_precision": round(m_p, 4), "macro_recall": round(m_r, 4),
    "n_test": n_test, "method": "closed_set",
}
with open(f"{DIRS['results']}/test_metrics.json", "w") as f:
    json.dump(metrics, f, indent=2)

# ── Confusion matrix ──────────────────────────────────────────────────────────
cm = confusion_matrix(test_true_names, pred_names, labels=LABEL_NAMES)
fig, ax = plt.subplots(figsize=(16, 14))
im = ax.imshow(cm, cmap="Blues")
ax.set_xticks(range(NUM_LABELS)); ax.set_yticks(range(NUM_LABELS))
ax.set_xticklabels(LABEL_NAMES, rotation=90, fontsize=7)
ax.set_yticklabels(LABEL_NAMES, fontsize=7)
ax.set_xlabel("Predicted"); ax.set_ylabel("True"); ax.set_title("Confusion Matrix (Closed-Set)")
fig.colorbar(im, shrink=0.8)
plt.tight_layout(); plt.savefig(f"{DIRS['plots']}/confusion_matrix.png", dpi=150); plt.show()

# ── Save predictions ──────────────────────────────────────────────────────────
pd.DataFrame({
    "text": test_texts, "true": test_true_names, "pred": pred_names,
    "true_code": test_true_codes, "pred_code": pred_codes,
    "correct": [t == p for t, p in zip(test_true_names, pred_names)],
}).to_csv(f"{DIRS['results']}/test_predictions.csv", index=False)
print(f"Predictions saved.")

"""## Block 14 — Error Analysis

Investigates: most confused pairs, neutral-vs-emotion confusion, over/under
predicted labels, per-class accuracy, and representative failures.
"""

print("=== Error Analysis ===\n")

res = pd.DataFrame({
    "text": test_texts, "true": test_true_names, "pred": pred_names,
    "correct": [t == p for t, p in zip(test_true_names, pred_names)],
})

errors = res[~res["correct"]]
print(f"Total errors: {len(errors):,} / {len(res):,} ({100*len(errors)/len(res):.1f}%)\n")

# ── Most confused pairs ───────────────────────────────────────────────────────
print("--- Top 15 Most Confused Pairs ---")
pairs = errors.groupby(["true", "pred"]).size().sort_values(ascending=False)
print(pairs.head(15).to_string())

# ── Specific confusions called out ────────────────────────────────────────────
confusion_pairs = [
    ("admiration", "gratitude"), ("anger", "annoyance"), ("confusion", "curiosity"),
    ("joy", "excitement"), ("approval", "disapproval"), ("neutral", "annoyance"),
]
print("\n--- Key Confusion Pairs ---")
for a, b in confusion_pairs:
    ab = len(errors[(errors["true"]==a) & (errors["pred"]==b)])
    ba = len(errors[(errors["true"]==b) & (errors["pred"]==a)])
    print(f"  {a:20s} <-> {b:20s}: {ab} + {ba} = {ab+ba}")

# ── Over/under predicted ──────────────────────────────────────────────────────
true_freq = Counter(test_true_names)
pred_freq = Counter(pred_names)
print("\n--- Over/Under Predicted ---")
for name in LABEL_NAMES:
    t, p = true_freq.get(name, 0), pred_freq.get(name, 0)
    ratio = p / max(t, 1)
    if ratio > 1.5 or ratio < 0.5:
        tag = "OVER" if ratio > 1 else "UNDER"
        print(f"  [{tag:5s}] {name:20s} true={t:4d} pred={p:4d} ratio={ratio:.2f}")

# ── Per-class accuracy ────────────────────────────────────────────────────────
print("\n--- Per-Class Accuracy ---")
for name in LABEL_NAMES:
    mask = res["true"] == name
    if mask.sum() > 0:
        ca = res[mask]["correct"].mean()
        print(f"  {name:20s}: {ca:.3f} (n={mask.sum()})")

# ── 10 Failures ───────────────────────────────────────────────────────────────
print("\n--- 10 Representative Failures ---")
for _, row in errors.sample(n=min(10, len(errors)), random_state=42).iterrows():
    print(f"  \"{row['text'][:90]}\"")
    print(f"    True: {row['true']} | Pred: {row['pred']}\n")

# ── Per-class F1 chart ────────────────────────────────────────────────────────
pcf1 = f1_score(test_true_names, pred_names, labels=LABEL_NAMES, average=None, zero_division=0)
fig, ax = plt.subplots(figsize=(14, 5))
ax.bar(range(NUM_LABELS), pcf1, color="teal")
ax.set_xticks(range(NUM_LABELS))
ax.set_xticklabels(LABEL_NAMES, rotation=45, ha="right", fontsize=7)
ax.set_ylabel("F1"); ax.set_title("Per-Class F1")
ax.axhline(m_f1, color="red", ls="--", label=f"Macro F1={m_f1:.3f}")
ax.legend(); ax.grid(axis="y", alpha=0.3)
plt.tight_layout(); plt.savefig(f"{DIRS['plots']}/per_class_f1.png", dpi=150); plt.show()

"""## Block 15 — Clean Inference Function

Returns human-readable label, class code, confidence, and optional explanation.
Classification accuracy does NOT depend on the explanation step.
"""

print("=== Inference Function ===\n")

EXPLAIN_PROMPT = (
    "You briefly explain emotion classifications. Given text and its classified emotion, "
    "explain in ONE sentence what textual cues support this. Stay grounded in the text. "
    "Do not make medical or diagnostic claims.\n"
    "Text: \"{text}\"\nEmotion: {label}\nExplanation:"
)

def predict(text: str, explain: bool = False, top_k: int = 3) -> dict:
    """Predict emotion via closed-set scoring. Explanation is a separate optional step."""
    name, code_str, scores = closed_set_predict(text)

    # Confidence from scores (softmax over log-probs)
    score_tensor = torch.tensor([scores[i] for i in range(NUM_LABELS)])
    probs = torch.softmax(score_tensor, dim=0)
    confidence = probs[NAME2IDX[name]].item()

    # Top-K
    top_k_indices = probs.argsort(descending=True)[:top_k]
    top_k_list = [{"label": IDX2NAME[i.item()], "code": IDX2CODE[i.item()],
                    "score": round(probs[i].item(), 4)} for i in top_k_indices]

    result = {
        "label": name, "code": code_str, "confidence": round(confidence, 4), "top_k": top_k_list,
    }

    if explain:
        exp_prompt = EXPLAIN_PROMPT.format(text=text[:250], label=name)
        exp_inputs = tokenizer(exp_prompt, return_tensors="pt", truncation=True,
                               max_length=config.max_seq_length).to(model.device)
        with torch.no_grad():
            exp_out = model.generate(**exp_inputs, max_new_tokens=80,
                                     do_sample=True, temperature=0.3, top_p=0.9)
        explanation = tokenizer.decode(
            exp_out[0][exp_inputs.input_ids.shape[1]:], skip_special_tokens=True
        ).strip().split(".")[0] + "."
        result["explanation"] = explanation

    return result

# Test
r = predict("I'm so happy that we finally finished!", explain=True, top_k=3)
print(json.dumps(r, indent=2))

"""## Block 16 — Save Artifacts"""

print("=== Save Artifacts ===\n")

model.save_pretrained(DIRS["model"])
tokenizer.save_pretrained(DIRS["model"])
print(f"Model saved to {DIRS['model']}")

cfg_dict = asdict(config)
with open(f"{DIRS['results']}/config.json", "w") as f:
    json.dump({k: str(v) for k, v in cfg_dict.items()}, f, indent=2)

with open(f"{DIRS['results']}/prompts.json", "w") as f:
    json.dump({"classify_template": PROMPT_TEMPLATE, "explain_template": EXPLAIN_PROMPT}, f, indent=2)

print("\nSaved files:")
for root, _, files in os.walk(config.output_dir):
    for fname in sorted(files):
        fp = os.path.join(root, fname)
        print(f"  {os.path.relpath(fp, config.output_dir):50s} {os.path.getsize(fp)/1e6:.2f} MB")

"""## Block 17 — GGUF Export & Ollama Deployment

Exports to GGUF for Ollama. Note: Ollama uses free generation, which is less
accurate than the closed-set Python scoring. For maximum accuracy, use the
`closed_set_predict()` function in Python. Ollama is for convenient local use.
"""

print("=== GGUF Export ===\n")

print("Exporting to GGUF (q4_k_m)...")
model.save_pretrained_gguf(DIRS["gguf"], tokenizer, quantization_method="q4_k_m")

print("Done.\n")
for f in sorted(os.listdir(DIRS["gguf"])):
    fp = os.path.join(DIRS["gguf"], f)
    if os.path.isfile(fp):
        print(f"  {f} ({os.path.getsize(fp)/1e6:.1f} MB)")

# ── Modelfile ─────────────────────────────────────────────────────────────────
label_ref = ", ".join(f"{IDX2CODE[i]}={LABEL_NAMES[i]}" for i in range(NUM_LABELS))

mf_lines = [
    "FROM ./unsloth.Q4_K_M.gguf",
    "",
    'TEMPLATE """{{ if .System }}<|start_header_id|>system<|end_header_id|>',
    "",
    "{{ .System }}<|eot_id|>{{ end }}<|start_header_id|>user<|end_header_id|>",
    "",
    "{{ .Prompt }}<|eot_id|><|start_header_id|>assistant<|end_header_id|>",
    "",
    '{{ .Response }}<|eot_id|>"""',
    "",
    'SYSTEM """You are an emotion classifier. Given text, identify the primary emotion.',
    "Label codes: " + label_ref + ".",
    "Respond with the label code and a brief explanation.",
    "Do NOT make medical or diagnostic claims.",
    '"""',
    "",
    "PARAMETER temperature 0.1",
    "PARAMETER top_p 0.9",
    'PARAMETER stop "<|eot_id|>"',
    "PARAMETER num_predict 100",
]

mf_path = f"{DIRS['gguf']}/Modelfile"
with open(mf_path, "w") as f:
    f.write("\n".join(mf_lines) + "\n")
print(f"\nModelfile saved to {mf_path}")

print("""
=== Ollama Deployment ===

cd /path/to/gguf/
ollama create emotion-v3 -f Modelfile
ollama run emotion-v3

NOTE: For maximum accuracy, use closed_set_predict() in Python.
Ollama free generation is convenient but less accurate.
""")

"""## Block 18 — Final Demo"""

print("=== Final Demo ===\n")

demos = [
    "I'm so proud of my daughter for graduating with honors!",
    "This is absolutely disgusting, how could they do this?",
    "I don't really have an opinion on that.",
    "I'm worried about the upcoming exam results.",
    "That movie was hilarious, I couldn't stop laughing!",
    "Thank you for always being there for me.",
    "I just lost my grandmother. I can't believe she's gone.",
    "Wait, they actually won?! I didn't see that coming!",
    "I shouldn't have said those things. I feel terrible.",
    "I really hope things get better from here.",
]

for i, text in enumerate(demos):
    r = predict(text, explain=True, top_k=3)
    print(f"[{i+1}] \"{text}\"")
    print(f"    {r['code']} = {r['label']} (conf={r['confidence']:.3f})")
    if r.get("explanation"):
        print(f"    Explanation: {r['explanation'][:120]}")
    alts = ", ".join(f"{d['code']}={d['label']}({d['score']:.2f})" for d in r["top_k"])
    print(f"    Top-3: {alts}\n")

print("=" * 60)
print("  FinalEmotionClassification_v3.ipynb — NOTEBOOK FINISHED")
print(f"  All outputs: {config.output_dir}")
print("=" * 60)

##Error Bar Chart Modification to Per-Class F1 Scores with 95% Confidence Intervals
# Figure 5 — Hardcoded per-class F1 scores with approximate 95% Wilson intervals
# F1 values and supports are taken from the saved classification report output.

import numpy as np
import matplotlib.pyplot as plt

LABEL_NAMES = [
    "admiration", "amusement", "anger", "annoyance", "approval",
    "caring", "confusion", "curiosity", "desire", "disappointment",
    "disapproval", "disgust", "embarrassment", "excitement", "fear",
    "gratitude", "grief", "joy", "love", "nervousness",
    "optimism", "pride", "realization", "relief", "remorse",
    "sadness", "surprise", "neutral"
]

# Per-class F1 scores from classification report
f1_scores = np.array([
    0.70, 0.82, 0.42, 0.28, 0.42,
    0.48, 0.37, 0.55, 0.53, 0.29,
    0.42, 0.54, 0.55, 0.40, 0.76,
    0.92, 0.00, 0.62, 0.82, 0.51,
    0.64, 0.20, 0.20, 0.00, 0.70,
    0.53, 0.55, 0.69
])

# Supports from classification report
supports = np.array([
    345, 186, 131, 194, 235,
    84, 97, 175, 56, 88,
    195, 76, 23, 54, 64,
    248, 2, 92, 153, 12,
    106, 7, 89, 7, 44,
    101, 87, 1594
])

macro_f1 = 0.4964


def wilson_interval(p, n, z=1.96):
    """
    Approximate Wilson score confidence interval.
    Here, p is the hardcoded F1 score and n is class support.
    """
    if n == 0:
        return 0.0, 0.0

    denominator = 1 + (z**2 / n)
    center = (p + (z**2 / (2 * n))) / denominator
    margin = (z / denominator) * np.sqrt(
        (p * (1 - p) / n) + (z**2 / (4 * n**2))
    )

    lower = max(0.0, center - margin)
    upper = min(1.0, center + margin)

    return lower, upper


lower_bounds = []
upper_bounds = []

for f1, n in zip(f1_scores, supports):
    if f1 == 0:
        # Keep zero-F1 classes from showing misleading huge upper error bars
        lower_bounds.append(0.0)
        upper_bounds.append(0.0)
    else:
        low, high = wilson_interval(f1, n)
        lower_bounds.append(low)
        upper_bounds.append(high)

lower_bounds = np.array(lower_bounds)
upper_bounds = np.array(upper_bounds)

lower_errors = f1_scores - lower_bounds
upper_errors = upper_bounds - f1_scores
yerr = np.vstack([lower_errors, upper_errors])


fig, ax = plt.subplots(figsize=(14, 5))

ax.bar(
    range(len(LABEL_NAMES)),
    f1_scores,
    color="teal",
    alpha=0.85,
    yerr=yerr,
    capsize=3,
    ecolor="black",
    error_kw={"elinewidth": 1}
)

ax.set_xticks(range(len(LABEL_NAMES)))
ax.set_xticklabels(LABEL_NAMES, rotation=45, ha="right", fontsize=7)

ax.set_ylabel("F1 Score")
ax.set_title("Per-Class F1 Scores with 95% Confidence Intervals")

ax.axhline(
    macro_f1,
    color="red",
    linestyle="--",
    linewidth=1.5,
    label=f"Macro F1 = {macro_f1:.4f}"
)

ax.set_ylim(0, 1.05)
ax.legend()
ax.grid(axis="y", alpha=0.3)

plt.tight_layout()
plt.savefig("per_class_f1_with_confidence_intervals.png", dpi=150)
plt.show()